const projects = [
  {
    id: 'O1i',
    category: 'web',
    title: 'MERNTasks Web',
    subtitle: 'Productivity App',
    image: './images/merntasks.webp',
    repository: 'https://github.com/tzivigelstein/MERNTasks-Client',
    site: 'https://mern-tasks-client.vercel.app/',
    stack: [
      { id: 'XH', name: 'React', color: '#5ed3f3' },
      { id: 'Ms', name: 'Node', color: '#7fc728' },
      { id: '4a', name: 'CSS', color: '#006bb4' },
    ],
  },
  {
    id: 'jyO',
    category: 'app',
    title: 'MERNTasks App',
    subtitle: 'Productivity App',
    image: './images/MERNTasksFlyer.webp',
    repository: '',
    site: '',
    stack: [
      { id: 'eI', name: 'React Native', color: '#03a3ce' },
      { id: 'K3', name: 'Node', color: '#7fc728' },
      { id: 'GQ', name: 'GraphQL', color: '#de33a6' },
    ],
  },
  {
    id: 'SGE',
    category: 'web',
    title: 'Tidify Web',
    subtitle: 'Food App',
    image: './images/TidifyFlyerWeb.webp',
    repository: 'https://github.com/tzivigelstein/Tidify-Host',
    site: 'https://tidify-app.vercel.app/',
    stack: [
      { id: 'im', name: 'React', color: '#5ed3f3' },
      { id: 'ce', name: 'CSS', color: '#006bb4' },
      { id: 'J8', name: 'Firebase', color: '#f7c62d' },
    ],
  },
  {
    id: 'lKc',
    category: 'app',
    title: 'Tidify App',
    subtitle: 'Food App',
    image: './images/TidifyFlyerApp.webp',
    repository: '',
    site: '',
    stack: [
      {
        id: 'JV',
        name: 'React Native',
        color: '#03a3ce',
      },
      {
        id: 'Go',
        name: 'Firebase',
        color: '#f7c62d',
      },
    ],
  },
  {
    id: '2Jp',
    category: 'web',
    title: 'Product Hunt',
    subtitle: 'Social App',
    image: './images/ProductHuntFlyer.webp',
    repository: 'https://github.com/tzivigelstein/Product-Hunt-Clone',
    site: 'https://producthunt-cl.vercel.app/',
    stack: [
      { id: 'sI', name: 'React', color: '#5ed3f3' },
      { id: 'Nq', name: 'Next', color: '#222' },
      { id: 'vZ', name: 'CSS', color: '#006bb4' },
      { id: 'n3', name: 'Firebase', color: '#f7c62d' },
    ],
  },
  {
    id: 'gCh',
    category: 'web',
    title: 'Twitter',
    subtitle: 'Social App',
    image: './images/TwitterCloneFlyer.webp',
    repository: 'https://github.com/tzivigelstein/Twitter-Clone',
    site: 'https://twitter-cl.vercel.app/login',
    stack: [
      { id: 'wf', name: 'React', color: '#5ed3f3' },
      { id: 'Lx', name: 'Next', color: '#222' },
      { id: 'gG', name: 'CSS', color: '#006bb4' },
      { id: 'Dv', name: 'Firebase', color: '#f7c62d' },
    ],
  },
  {
    id: 'lt4',
    category: 'app',
    title: 'Crypto',
    subtitle: 'Productivity App',
    image: './images/CryptoFlyer.webp',
    repository: 'https://github.com/tzivigelstein/Twitter-Clone',
    site: 'https://twitter-cl.vercel.app/login',
    stack: [
      {
        id: 'JV',
        name: 'React Native',
        color: '#03a3ce',
      },
    ],
  },
]

export default projects
